# 显示
显示.启用=true
显示.玩家名称前显示=true
显示.加入消息显示=false
显示.前缀位置=before-name
显示.已绑定文本=[green][已绑定][]
显示.未绑定文本=[scarlet][未绑定][]
显示.已绑定颜色=green
显示.未绑定颜色=scarlet

# 数据
数据.绑定列表名称=player_bind
数据.comid字段=comid
数据.状态字段=bound
数据.来源字段=bindSource
数据.时间字段=bindTime

# 检测
检测.优先使用外部接口=true
检测.API模块名称=bind-query
检测.允许其他插件直接调用=true
检测.玩家进入时自动检查=true
检测.检查超时毫秒=3000
