display.enabled=true
display.prefixBeforeName=true
display.boundText=[green][\u5df2\u7ed1\u5b9a][]
display.unboundText=[scarlet][\u672a\u7ed1\u5b9a][]

data.bindListName=player_bind
data.comidField=comId
data.boundField=bound
data.sourceField=bindSource
data.timeField=bindTime

query.profileByComid=bind-local-by-comid
query.profileByUuid=bind-local-by-uuid

check.autoCheckOnJoin=true
